version: "3.3"
services:
  gstreamer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gst-plugin-build
    volumes:
      - ./target:/target
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      RUNNER: 'local'
