name: build debian package
on: [push]
jobs:
   build-debian-package:
      runs-on: ubuntu-latests
      container:
        image: mariolukas/gst-plugins-rs-compile
      steps:
        - uses: actions/checkout@v2
        - name: Building debian packages
          run: ./entrypoint.sh