name: build debian package
on: [push]
jobs:
   build-debian-package:
      runs-on: ubuntu-latest
      container:
        image: mariolukas/gst-plugins-rs-compile
        env:
          RUNNER: 'git'
      steps:
        - name: wget entrypoint.sh script from repo
          uses: wei/wget@v1
          with:
            args: -O entrypoint.sh -P ./ https://raw.githubusercontent.com/mariolukas/gst-plugins-rs-builder/main/entrypoint.sh
        #- uses: actions/checkout@v2
        - name: make entrypoint.sh executable
          run: chmod a+x entrypoint.sh
        - name: Building debian packages
          run: ./entrypoint.sh
        - name: Create Release
          uses: actions/github-script@v2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              console.log('environment', process.versions);
              
              const fs = require('fs').promises;
              
              const { repo: { owner, repo }, sha } = context;
              console.log({ owner, repo, sha });
              
              const releaseDate = new Date()
              releaseDate.toISOString().split('T')[0]
              
              const release = await github.repos.createRelease({
                owner, repo,
                tag_name: releaseDate,
                draft: true,
                target_commitish: sha
              });
        
              console.log('created release', { release });
          
              for (let file of await fs.readdir('/target/*.deb')) {
                console.log('uploading', file);
        
                await github.repos.uploadReleaseAsset({
                  owner, repo,
                  release_id: release.data.id,
                  name: file,
                  data: await fs.readFile(`./${file}`)
                });            
              }
